http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.local`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.local"
            sans:
              - "*.docker.local"
          - main: "home.local"
            sans:
              - "*.home.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
